[package]
name = "gpx"
description = "Rust read/write support for GPS Exchange Format (GPX)"
license = "MIT"
version = "0.8.2"
authors = ["Brendan Ashworth <brendan.ashworth@me.com>", "Corey Farwell <coreyf@rwell.org>", "Felix Gruber <felgru@gmx.de>"]
readme = "README.md"
documentation = "https://docs.rs/gpx"
repository = "https://github.com/georust/gpx"
edition = "2018"

[dependencies]
assert_approx_eq = "1"
chrono = "0.4"
error-chain = "0.12"
geo-types = "0.7"
xml-rs = "0.8"

[dev-dependencies]
geo = "0.18"
